### ISSUE TITLE
predictive_load does not respect `inherit` feature of `has_one`

### ISSUE THREAD

**Issue by smedberg** [zendesk/predictive_load#11]
We have a gem that includes class MainClass with a line like this:

``` ruby
has_one :other_class, primary_key: :first_id, foreign_key: :first_id, inherit: [:second_id, :third_type]
```

That gem is loaded in a Rails project which uses predictive_load.

When we execute:

``` ruby
MainClass.all.map(&:other_class)
```

predictive_load runs SQL like:

```
SELECT `other_class`.* FROM `other_class` WHERE `other_class`.`first_id` IN (<first ID 1>, <first ID 2>)
```

Note that the generated SQL constrains on `other_class.first_id`, but not on `other_class.second_id` or `other_class.third_type`.  Our table is indexed on [`second_id`, `third_type`, `first_id`], and our DB doesn't use that index when looking up by `first_id`.  This causes a full table scan, and is causing production outages.

Our solution is to update our code to look like:

``` ruby
has_one :other_class, primary_key: :first_id, foreign_key: :first_id, inherit: [:second_id, :third_type], predictive_load: false
```

This seems to work fine- the erroneous SQL is no longer generated.

However, it's unfortunate that our gem code had no obvious bugs, and passed all tests in isolation, but caused a production outage when loaded into a Rails app that uses predictive_load.  I'd prefer that either predictive_load respect the `inherit` keyword or (arguably better), that predictive_load raise an exception or turn itself off when it sees keywords that it does not recognize.

**Comment by grosser** [comment]
That's active_record_inherit_assoc gem at work ... which is not supported
here ... so add it and then create a failing testcase / try to fix it ?

Having it raise on unknown keywords would be good too ... and then prompt
users to either add it to 'ignored' or 'disabled' set.
